kind: Service
apiVersion: v1
metadata:
  name: acceleration-calc
spec:
  selector:
    app: acceleration-calc
  type: NodePort
  ports:
  - name: "3000"
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
