apiVersion: apps/v1
kind: Deployment
metadata:
  name: acceleration-deployment-dv-{{ .Release.Name }}
  labels:
    app: {{.Values.container.label_app}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{.Values.container.label_app}}
  template:
    metadata:
      labels:
        app: {{.Values.container.label_app}}
    spec:
      containers:
      - name: {{ .Values.container.label_app }}-{{ .Release.Name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        ports:
        - name: {{ .Values.service.targetPort}}
          containerPort: {{ .Values.container.containerPort }}
