apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: acceleration-ingress
    annotations:
         nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /cal
        backend:
          serviceName: acc-cal-service
          servicePort: {{ .Values.service.port}}
