
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: acceleration-ingress
  annotations:
    http.port: "3000"
spec:
  rules:
  - http:
      paths:
      - path: /calc
        backend:
          serviceName: acc-cal-service
          servicePort: 3000
