apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: acceleration-calc
spec:
    replicas: {{ .Values.replicas }}
    template:
        metadata:
            labels:
                app: {{.Values.container.label_app}}
        spec:
            containers:
            - name: acceleration-calc-{{ .Release.Name }}
              image: {{ .Values.container.image }}
              imagePullPolicy: {{ .Values.container.imagePullPolicy }}
              env:
                 - name: DV_URL
                   value: "http://acceleration-dv-service-{{ .Release.Name }}:3001/dv"
                 - name: A_URL
                   value: "http://acceleration-a-service-{{ .Release.Name }}:3002/a"
                 - name: RUNTIME_ENV
                   value: {{ .Values.runtime }}
              ports:
                  - containerPort: {{ .Values.container.port_ingress }}
              livenessProbe:
                httpGet:
                  path: /health
                  port: {{ .Values.container.port_ingress }}
                  initialDelaySeconds: 5
                  periodSeconds: 5
              readinessProbe:
                httpGet:
                  path: /health
                  port: {{ .Values.container.port_ingress }}
                  initialDelaySeconds: 5
                  periodSeconds: 5