# Default values for acceleration-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 2

image:
  repository: vault60/acceleration-calc
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  name: acceleration-app
  type: NodePort
  externalPort: 3000
  internalPort: 3000

ingress:
  enabled: false
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  hosts:
    - host: acceleration-calc.local
      paths: ['/']

  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
